//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jenk_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class companyInfo
    {
        public int id { get; set; }
        public string companyName { get; set; }
        public Nullable<int> employeeCount { get; set; }
    }
}
